FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json /app/frontend/
RUN cd /app/frontend && npm install

COPY frontend /app/frontend
WORKDIR /app/frontend

ENV NODE_ENV=production

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
